#!/usr/bin/env node
// Generate web/spa.js — the tables engine.js imports.
//
// Everything here comes from files checked into the repo (tools/spa_meta.json and
// claims.json), not from the game, so a fresh clone can run the tests without an
// EverQuest install. The site build calls this too.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { load as loadClaims, byType, spasOf, isActionable } from './claims.mjs';
import { MAX_PLAYER_LEVEL } from './spells.mjs';
import { resolveNames, focusSpas, focusLimitSpas } from './spa_names.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.dirname(HERE);

export function generate() {
  const spaMeta = JSON.parse(fs.readFileSync(path.join(HERE, 'spa_meta.json'), 'utf8'));
  const { names: spaNames, fallback } = resolveNames(spaMeta.spa_names);

  const claimsDoc = loadClaims();
  const nonCumulative = byType(claimsDoc, 'non_cumulative').sort((a, b) => a.spa - b.spa);
  const spas = nonCumulative.map(c => c.spa);
  const confirmed = nonCumulative.filter(c => c.status === 'confirmed').map(c => c.spa);
  // How confident each one is, so a view can name the value that applies without
  // presenting an unverified claim in the same voice as a confirmed one.
  const ncStatus = Object.fromEntries(nonCumulative.map(c => [c.spa, c.status]));
  // Haste is a percentage of normal speed, so 100 is "no change" and the bonus
  // EQEmu compares is value - 100. Without that, a 90 (a slow) reads as a bonus.
  const ncOffset = Object.fromEntries(nonCumulative.filter(c => c.offset).map(c => [c.spa, c.offset]));
  // What happens when the two values sit on opposite sides of zero. Usually nothing
  // can be said — neither displaces the other on its own terms, so the server decides
  // by order. Haste is the exception: a slow takes the slot outright.
  const ncMixed = Object.fromEntries(nonCumulative.filter(c => c.mixed).map(c => [c.spa, c.mixed]));

  // Focus effects, from Daybreak's own Fc_ and Ff_ prefixes, unioned with the set
  // EQEmu treats as focus. Naming by EQEmu's enum would miss the legacy-named foci;
  // Daybreak's list names every one of EQEmu's as Fc_/Ff_ and adds three more.
  const focusEffects = spaMeta.focus_effects || [];
  const focusSpaList = focusSpas([...focusEffects, ...(spaMeta.focus_limits || [])]);
  // The limiter subset, so a focus can be told apart from the thing narrowing it.
  const focusLimitList = focusLimitSpas(spaMeta.focus_limits || []);

  // Foci where only the best applies to a cast, minus the procs that all fire.
  const bestOnlyClaim = byType(claimsDoc, 'focus_best_only')[0];
  const focusExceptions = bestOnlyClaim ? bestOnlyClaim.exceptions : [];
  const focusBestOnly = bestOnlyClaim ? focusSpaList.filter(id => !focusExceptions.includes(id)) : [];

  // Focus SPAs missing from the client-derived ignore list.
  //
  // What happens to them depends on the claim's evidence, which is the whole point
  // of claims.json. Once the claim is actionable — a primary source, or a named
  // practitioner — the engine exempts them like any other ignored SPA, and verdicts
  // change. While it is only unverified, they are still arbitrated and any verdict
  // resting on one is flagged doubtful instead.
  const stackingClaims = byType(claimsDoc, 'focus_stacking');
  const declared = stackingClaims.flatMap(spasOf);
  const wildcard = stackingClaims.some(c => Array.isArray(c.spas) && c.spas.length === 0);
  const pool = wildcard ? [...new Set([...focusSpaList, ...declared])] : declared;
  const unlisted = pool.filter(id => !spaMeta.ignored_in_stacking.includes(id)).sort((a, b) => a - b);
  const acted = stackingClaims.length > 0 && stackingClaims.every(isActionable);
  const exemptedByClaim = acted ? unlisted : [];
  const contested = acted ? [] : unlisted;

  const js = '// generated by tools/gen_spa_js.mjs — do not edit\n'
    + `export const SPA_NAMES = ${JSON.stringify(spaNames)};\n`
    + `export const IGNORED_IN_STACKING = ${JSON.stringify(spaMeta.ignored_in_stacking)};\n`
    + `export const NON_CUMULATIVE_SPA = ${JSON.stringify(spas)};\n`
    + `export const NON_CUMULATIVE_CONFIRMED = ${JSON.stringify(confirmed)};\n`
    + `export const NON_CUMULATIVE_STATUS = ${JSON.stringify(ncStatus)};\n`
    + `export const NON_CUMULATIVE_OFFSET = ${JSON.stringify(ncOffset)};\n`
    + `export const NON_CUMULATIVE_MIXED = ${JSON.stringify(ncMixed)};\n`
    + `export const IGNORED_BY_CLAIM = ${JSON.stringify(exemptedByClaim)};\n`
    + `export const FOCUS_SPA = ${JSON.stringify(focusSpaList)};\n`
    + `export const FOCUS_BEST_ONLY = ${JSON.stringify(focusBestOnly)};\n`
    + `export const FOCUS_LIMIT = ${JSON.stringify(focusLimitList)};\n`
    + `export const FOCUS_PROC_EXCEPTIONS = ${JSON.stringify(focusExceptions)};\n`
    + `export const FOCUS_CONTESTED = ${JSON.stringify(contested)};\n`
    + `export const MAX_PLAYER_LEVEL = ${MAX_PLAYER_LEVEL};\n`;
  fs.writeFileSync(path.join(ROOT, 'web', 'spa.js'), js);
  return { spaNames, spas, confirmed, nonCumulative, focusSpas: focusSpaList, focusBestOnly, focusLimit: focusLimitList, focusExceptions, contested, exemptedByClaim, fallback };
}

// `file://${process.argv[1]}` looks equivalent but is not: on Windows argv[1] is a
// backslashed drive path, so that comparison never matches and the script silently
// does nothing. pathToFileURL is the portable form.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const r = generate();
  console.log(`web/spa.js written — SPA names from Daybreak's list`
            + (r.fallback.length ? ` (${r.fallback.length} falling back to EQEmu)` : '')
            + `, ${r.focusSpas.length} focus SPAs, ${r.spas.length} non-cumulative `
            + `(${r.confirmed.length} confirmed), ${r.exemptedByClaim.length} exempted by claim, `
            + `${r.contested.length} still contested`);
}
