#!/usr/bin/env node
// Generate web/spa.js — the tables engine.js imports.
//
// Everything here comes from files checked into the repo (tools/spa_meta.json and
// claims.json), not from the game, so a fresh clone can run the tests without an
// EverQuest install. The site build calls this too.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { load as loadClaims, byType } from './claims.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.dirname(HERE);

export const prettySpa = name => name
  .replace(/_/g, ' ')
  .replace(/(?<=[a-z0-9])(?=[A-Z])/g, ' ')
  .replace(/(?<=[A-Z])(?=[A-Z][a-z])/g, ' ')
  .replace(/\s+/g, ' ')
  .trim();

export function generate() {
  const spaMeta = JSON.parse(fs.readFileSync(path.join(HERE, 'spa_meta.json'), 'utf8'));
  const spaNames = Object.fromEntries(Object.entries(spaMeta.spa_names).map(([k, v]) => [k, prettySpa(v)]));

  const nonCumulative = byType(loadClaims(), 'non_cumulative').sort((a, b) => a.spa - b.spa);
  const spas = nonCumulative.map(c => c.spa);
  const confirmed = nonCumulative.filter(c => c.status === 'confirmed').map(c => c.spa);

  const js = '// generated by tools/gen_spa_js.mjs — do not edit\n'
    + `export const SPA_NAMES = ${JSON.stringify(spaNames)};\n`
    + `export const IGNORED_IN_STACKING = ${JSON.stringify(spaMeta.ignored_in_stacking)};\n`
    + `export const NON_CUMULATIVE_SPA = ${JSON.stringify(spas)};\n`
    + `export const NON_CUMULATIVE_CONFIRMED = ${JSON.stringify(confirmed)};\n`;
  fs.writeFileSync(path.join(ROOT, 'web', 'spa.js'), js);
  return { spaNames, spas, confirmed, nonCumulative };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { spas, confirmed } = generate();
  console.log(`web/spa.js written — ${spas.length} non-cumulative SPAs, ${confirmed.length} confirmed`);
}
