#!/usr/bin/env node
// Generate web/spa.js — the tables engine.js imports.
//
// Everything here comes from files checked into the repo (tools/spa_meta.json and
// claims.json), not from the game, so a fresh clone can run the tests without an
// EverQuest install. The site build calls this too.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { load as loadClaims, byType, spasOf } from './claims.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.dirname(HERE);

export const prettySpa = name => name
  .replace(/_/g, ' ')
  .replace(/(?<=[a-z0-9])(?=[A-Z])/g, ' ')
  .replace(/(?<=[A-Z])(?=[A-Z][a-z])/g, ' ')
  .replace(/\s+/g, ' ')
  .trim();

export function generate() {
  const spaMeta = JSON.parse(fs.readFileSync(path.join(HERE, 'spa_meta.json'), 'utf8'));
  const spaNames = Object.fromEntries(Object.entries(spaMeta.spa_names).map(([k, v]) => [k, prettySpa(v)]));

  const claimsDoc = loadClaims();
  const nonCumulative = byType(claimsDoc, 'non_cumulative').sort((a, b) => a.spa - b.spa);
  const spas = nonCumulative.map(c => c.spa);
  const confirmed = nonCumulative.filter(c => c.status === 'confirmed').map(c => c.spa);

  // Focus effects, taken from EQEmu's Mob::IsFocusEffect rather than guessed from
  // names — several foci predate the Fc_ convention (ImprovedDamage,
  // SympatheticProc, TriggerOnCast) and a name test would miss them. Focus limits
  // are folded in because they collide in slots the same way.
  const focusEffects = spaMeta.focus_effects || [];
  const focusSpas = [...new Set([...focusEffects, ...(spaMeta.focus_limits || [])])].sort((a, b) => a - b);

  // Foci where only the best applies to a cast, minus the procs that all fire.
  const bestOnlyClaim = byType(claimsDoc, 'focus_best_only')[0];
  const focusExceptions = bestOnlyClaim ? bestOnlyClaim.exceptions : [];
  const focusBestOnly = bestOnlyClaim ? focusEffects.filter(id => !focusExceptions.includes(id)) : [];

  // Focus SPAs the engine still arbitrates because they are missing from the
  // client-derived ignore list. A verdict resting on one of these is contested.
  // Derived rather than listed, so it tracks a regenerated spa_meta.json; a claim
  // may also name SPAs explicitly, and those are unioned in.
  const stackingClaims = byType(claimsDoc, 'focus_stacking');
  const declared = stackingClaims.flatMap(spasOf);
  const wildcard = stackingClaims.some(c => Array.isArray(c.spas) && c.spas.length === 0);
  const pool = wildcard ? [...new Set([...focusSpas, ...declared])] : declared;
  const contested = pool.filter(id => !spaMeta.ignored_in_stacking.includes(id)).sort((a, b) => a - b);

  const js = '// generated by tools/gen_spa_js.mjs — do not edit\n'
    + `export const SPA_NAMES = ${JSON.stringify(spaNames)};\n`
    + `export const IGNORED_IN_STACKING = ${JSON.stringify(spaMeta.ignored_in_stacking)};\n`
    + `export const NON_CUMULATIVE_SPA = ${JSON.stringify(spas)};\n`
    + `export const NON_CUMULATIVE_CONFIRMED = ${JSON.stringify(confirmed)};\n`
    + `export const FOCUS_SPA = ${JSON.stringify(focusSpas)};\n`
    + `export const FOCUS_BEST_ONLY = ${JSON.stringify(focusBestOnly)};\n`
    + `export const FOCUS_PROC_EXCEPTIONS = ${JSON.stringify(focusExceptions)};\n`
    + `export const FOCUS_CONTESTED = ${JSON.stringify(contested)};\n`;
  fs.writeFileSync(path.join(ROOT, 'web', 'spa.js'), js);
  return { spaNames, spas, confirmed, nonCumulative, focusSpas, focusBestOnly, focusExceptions, contested };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { spas, confirmed, focusSpas, contested } = generate();
  console.log(`web/spa.js written — ${spas.length} non-cumulative SPAs (${confirmed.length} confirmed), `
            + `${focusSpas.length} focus SPAs, ${contested.length} contested for stacking`);
}
